# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  vmImage: MiPcAgent

jobs:
- job: SaveFilesToGitHub
  displayName: 'Save Files to GitHub'
  steps:
  - checkout: self

  # Your build and test steps go here
  
  - script: |
      # Create a directory to store files
      mkdir FilesToSave
      
      # Copy files to the directory
      C:\XCELERA\EVIDENCE\24173_PlanEjecucionVictorEscobar\2067\17859_SuiteEntrenamiento\179734
      
      # Initialize a Git repository in the build directory
      git init
      git config --global user.email "vlopez@gmail.com"
      git config --global user.name "vlopez888"

      # Add the files to the Git repository
      git add C:\XCELERA\EVIDENCE\24173_PlanEjecucionVictorEscobar\2067\17859_SuiteEntrenamiento\179734

      # Commit the changes
      git commit -m "Add files to GitHub repository"

      # Set up the GitHub repository URL
      git remote add origin https://github.com/vlopez888/CargaEvidencia.git

      # Push changes to GitHub
      git push -u origin main
    displayName: 'Save files to GitHub'

