# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool: MiPcAgent

jobs:
- job: SaveFilesToGitHub
  displayName: 'Guardar Archivos en GitHub'
  steps:
  - checkout: self
  
  - script: |
      displayName: 'guardar en GitHub'
      git version
      git init
      cd workspace
      ls
      

